apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: note-app
  name: note-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: note-app
    spec:
      initContainers:
      - name: migration
        image: us-central1-docker.pkg.dev/wolfi-notes/wolfi-notes/webapp:latest
        command: ["python", "manage.py", "migrate"]
        envFrom:
        - configMapRef:
            name: webapp-config
        env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
      containers:
      - image: us-central1-docker.pkg.dev/wolfi-notes/wolfi-notes/webapp:latest
        name: note-app
        envFrom:
        - configMapRef:
            name: webapp-config
        env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 8000
        resources: {}
status: {}
