steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/wolfi-notes/webapp:$COMMIT_SHA', 
           './notes-app']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/${PROJECT_ID}/wolfi-notes/webapp:$COMMIT_SHA']
options:
  logging: CLOUD_LOGGING_ONLY
