package:
  name: postgresql-14
  version: "14.8"
  epoch: 1
  description: A sophisticated object-relational DBMS
  copyright:
    - license: BSD

environment:
  contents:
    repositories:
    - https://packages.wolfi.dev/bootstrap/stage3
    - https://packages.wolfi.dev/os
    keyring:
    - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - openssl-dev
      - libedit-dev
      - zlib-dev
      - libxml2-dev
      - bison
      - flex
      - execline-dev
      - util-linux-dev

pipeline:
  - uses: fetch
    with:
      expected-sha256: 39d38f0030737ed03835debeefee3b37d335462ce4995e2497bc38d621ebe45a
      uri: https://ftp.postgresql.org/pub/source/v${{package.version}}/postgresql-${{package.version}}.tar.bz2

  - uses: autoconf/configure
    with:
      opts: |
        --mandir=/usr/share/man \
        --with-openssl \
        --with-libedit-preferred \
        --with-uuid=e2fs

  # MAKELEVEL=0 is used because of a postgresql build system bug:
  # https://www.postgresql.org/message-id/15407-7b64e5de97dedc5e%40postgresql.org
  - uses: autoconf/make
    with:
      opts: MAKELEVEL=0

  - uses: autoconf/make-install

  # the official postgres image listens on all interfaces by default, let's do the same for consistency
  - runs: |
      sed -ri "s!^#?(listen_addresses)\s*=\s*\S+.*!\1 = '*'!" ${{targets.destdir}}/usr/share/postgresql/postgresql.conf.sample
      grep -F "listen_addresses = '*'" ${{targets.destdir}}/usr/share/postgresql/postgresql.conf.sample

  - uses: strip

subpackages:
  - name: postgresql-14-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - postgresql-14
        - openssl-dev
        - postgresql-14-client
        - libpq-14
    description: postgresql dev

  - name: postgresql-14-client
    description: PostgreSQL client
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv ${{targets.destdir}}/usr/bin/psql ${{targets.subpkgdir}}/usr/bin/

  - name: postgresql-14-contrib
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}
          make DESTDIR=${{targets.subpkgdir}} -C contrib install
    description: Extension modules distributed with PostgreSQL

  - name: libpq-14
    description: PostgreSQL libraries
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libpq.so* ${{targets.subpkgdir}}/usr/lib/

#  - name: postgresql-14-oci-entrypoint
#    description: Entrypoint for using PostgreSQL in OCI containers
#    dependencies:
#      runtime:
#        - bash
#    pipeline:
#      - runs: |
#          mkdir -p ${{targets.subpkgdir}}/var/lib/postgres/initdb
#          cp postgresql-entrypoint.sh ${{targets.subpkgdir}}/var/lib/postgres/initdb/
#          chmod +x ${{targets.subpkgdir}}/var/lib/postgres/initdb/postgresql-entrypoint.sh

update:
  enabled: true
  version-separator: _
  github:
    identifier: postgres/postgres
    strip-prefix: REL_
    tag-filter: REL_14
    use-tag: true
