name: Image digest update

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write 
      pull-requests: write
      id-token: write 

    steps:
    - uses: actions/checkout@v4
    - uses: chainguard-dev/setup-chainctl@main
      with:
        identity: "8db1c02f42c500d4c158df58938ea71dbe2d3c12/7ec62e11aab6d50d"
    - name: update digests
      uses: chainguard-dev/digestabot@v1.0.2
      with:
        token: ${{ secrets.PR_TOKEN }}
        signoff: true
        use-gitsign: true
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com> # optional
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        title-for-pr: 'Update Digests'
        commit-message: 'Update Digests'
        branch-for-pr: digestabot
        labels-for-pr: ''
