name: Image digest update

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write # to push the updates
      pull-requests: write # to open Pull requests
      id-token: write # used to sign the commits using gitsign

    steps:
    - uses: actions/checkout@v4
    - uses: chainguard-dev/digestabot@v1.0.2
      with:
        token: ${{ secrets.CG_PULL_TOKEN }}
        signoff: true 
        author: digestabot
        committer: digestabot
        labels-for-pr: automated pr, kind/cleanup, release-note-none 
        branch-for-pr: update-digests
        title-for-pr: Update images digests 
        description-for-pr: commit-message
        commit-message: Update images digests
